import { SideBar } from "@/components";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
          <SideBar />
          <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
